### ISSUE TITLE
How Long ?

### ISSUE THREAD

**Issue by gaurovsoni** [fluentpython/example-code-2e#19]
how long should i wait for 2nd edition? its been 1 yr + already.

**Comment by ramalho** [comment]
Thank you for your interest.

The 2nd edition is scheduled for release in April, 2022. I delivered the complete manuscript in November, 2021. It's now in the hands of O'Reilly and they don't delay.

The complete unrevised manuscript is available at O'Reilly Learning:

https://learning.oreilly.com/library/view/fluent-python-2nd/9781492056348/
