### ISSUE TITLE
Is the book going to change anymore?

### ISSUE THREAD

**Issue by Gr3Kidd3r** [fluentpython/example-code-2e#29]
Hi @ramalho 
I wanted to know at which stage the book is. Is it finished and revised? Cause the early access badge is gone on the book's page on O'Rielly's website.

**Comment by ramalho** [comment]
**Fluent Python Second Edition** was released in April 2022. Except for small fixes, there will be no changes until a major update for the **Third Edition**, which is not yet scheduled to start and is unlikely to appear before 2025.
